
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'people_counting_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  people_counting_project:
      # Applies to all files under models/example/
      #tcs:
      #  materialized: table
      #  +enabled: false
      #dim_tables:
      #  +enabled: true


vars: 
  # HIGH_WATERMARK - default high watermark for partition filter
  HIGH_WATERMARK: "1975-01-01"
  # process_time_interval_from - window on how far back to check from source tables. Play around with value in dev to get results
  process_time_interval_from: 1 DAY
  batch_id: "{{ invocation_id }}"
  # processed_timestamp - job start time. will default to run_started_at(dbt var) if none is provided
  processed_timestamp: "{{ run_started_at.strftime(\"%Y-%m-%d %H:%M:%S %Z\") }}"
  PROCESS_BATCH_ID: "{{ invocation_id }}"
  null_column_val: 'NULL'
  null_in_hash_column_val: '6c3e226b4d4795d518ab341b0824ec29'
  numeric_column_default: 0
  numeric_low_value: -1
  day_zero_start_date: 20190101
  day_zero_end_date: 20210831
  Day0_Run_Flag: True
  text_column_default: Unknown